#####
## For explanation of YAML syntax, see https://learnxinyminutes.com/docs/yaml/
## In addition, ravshello supports a non-standard "!include" extension, e.g.:
##     KEY: !include /PATH/FILE
## Such inclusions will be handled recursively so use with care.


######
## Optionally specify login credentials for Ravello account to avoid prompting

#ravelloUser: me@example.com
#ravelloPass: my cr@zy passw0rd, no quotes required


######
## If present, *nickname* will be used as the ravshello 'user', overriding the
## default behavior of determining this from the system user (note that this
## nickname directive can in turn be overriden by the cmdline --nickname opt).

#nickname: myNickName


######
## Optionally declare MULTIPLE sets of Ravello credentials and map them to
## profile names. The names are arbitrary and can be selected by use of
## the -u or --user cmdline option. Notes:
##  - *ravelloUser* is required.
##  - *ravelloPass* is not required. (Will be prompted for pass.)
##  - *nickname* is not required.
##  - *defaultProfile* is not required.

#userProfiles:
#    bob:
#        ravelloUser: bob@example.com
#        ravelloPass: xxxxx
#    ana:
#        ravelloUser: anabanana@example.com
#        ravelloPass: xxxxx
#        nickname: ana
#    wow@example:
#        ravelloUser: wow@example.com
#    defaultProfile: ana


######
## Optionally specify additional text to be displayed when login fails.

#unableToLoginAdditionalMsg: Ohmg contact bob at the helpdesk!


######
## If present, *sshKeyFile* is integrated into the ssh command reported to the
## user by ravshello's query_app_status command.

#sshKeyFile: /expected/path/to/ssh/priv/key


######
## If present, *eventsOfInterest* overrides rav-notify's default list of
## events to watch for. Remove existing lines and/or add new ones.

eventsOfInterest:
    - APP_TIMEOUT_AUTO_STOPPING
    - APP_TIMEOUT_AUTO_STOPPED
    - APPLICATION_TIMER_RESET
    - APPLICATION_DELETED
    - VM_STOPPED
    - VM_STARTED
    - VM_SNAPSHOTTING_AFTER_STOP
    - VM_FINISHED_SNAPSHOTTING


######
## If present, each cmdline in *preRunCommands* will be executed prior to
## any cmds present on argv and prior to entering the interactive shell but
## ONLY in admin mode and when no -s SCRIPTFILE option is present.

#preRunCommands:
#    - /blueprints refresh
#    - cd /apps
#    - ls
#    - (ADD AS MANY COMMANDS AS YOU WANT)


######
## Setting this boolean true changes the default behavior of prompting for
## missing Ravello credentials -- instead, ravshello will exit with login error.
## This can also be set true by use of --never-prompt-creds cmdline option.

#neverPromptCreds: false


######
## Optionally include additional config file(s). These must be the same format
## as above. Keys from included config files will overwrite keys from earlier
## files. Inclusion is not recursive (included files don't support `includes`),
## Globbing and tilde-expansion ARE supported.

#includes:
#    - ~/some/file
#    - /another/dir/*
